<a target="_blank" href="https://colab.research.google.com/github/LPolyakova/Linear_Algebra_for_CS_students/blob/main/CP/LA_CP_04_Linear_spaces.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# ЛА-Комп'ютерний практикум-04. Лінійні простори

In [1]:
# these imports may be useful

import pandas as pd
from scipy import linalg
import numpy as np
import matplotlib.pyplot as plt
from sympy import *                  #module to do symbolic calculations

 #### Деякі інструменти, що стануть у нагоді 

In [2]:
# these tools may be useful

# rank calculation
A = np.array([[1,2], [-1, -2], [2, 4]]) 
r = np.linalg.matrix_rank(A)
print(f"A={A}, \n rank(A) = {r}")

A=[[ 1  2]
 [-1 -2]
 [ 2  4]], 
 rank(A) = 1


## Вправи

💻  **4.1. Розклад за базисом.** Напишіть програму, яка перевіряє, чи є набір векторів $a_1, a_2, \dots, a_n$ базисом простору $\mathbb{R}^n$, і знаходить розклад вектора $b$ за цим базисом. Ви можете використовувати numpy.linalg.solve

    "💻  **4.1. Розклад за базисом.** Напишіть програму, яка перевіряє, чи є набір векторів $a_1, a_2, \\dots, a_n$ базисом простору $\\mathbb{R}^n$, і знаходить розклад вектора $b$ за цим базисом. Ви можете використовувати numpy.linalg.solve"


    "💻  **4.1. Розклад за базисом.** Напишіть програму, яка перевіряє, чи є набір векторів $a_1, a_2, \\dots, a_n$ базисом простору $\\mathbb{R}^n$, і знаходить розклад вектора $b$ за цим базисом. Ви можете використовувати numpy.linalg.solve"


In [1]:
#write your code here

import numpy as np
from numpy.linalg import LinAlgError

def is_basis_and_decompose(vectors, b):
    """
    vectors: список векторів (кожен вектор — список або np.array)
    b: вектор, який потрібно розкласти
    """

    A = np.column_stack(vectors)  # матриця, у якій вектори — стовпці
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)

    print("Матриця базису A:")
    print(A)
    print("\nВектор b:")
    print(b)

    try:
        # перевіримо, чи матриця невироджена (тобто det ≠ 0)
        det = np.linalg.det(A)
        print(f"\nВизначник матриці A: {det}")

        if np.isclose(det, 0):
            print("Вектори не утворюють базис: визначник дорівнює нулю.")
            return

        # Розв'язуємо A * x = b
        x = np.linalg.solve(A, b)
        print("\nРозклад вектора b за базисом:")
        for i, coeff in enumerate(x):
            print(f"  {coeff:.4f} * a_{i+1}")
        return x

    except LinAlgError as e:
        print("Помилка при обчисленні:", e)

# Приклад використання
a1 = [1, 0, 0]
a2 = [0, 1, 0]
a3 = [0, 0, 1]
b = [2, -3, 5]

vectors = [a1, a2, a3]
is_basis_and_decompose(vectors, b)


Матриця базису A:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Вектор b:
[ 2. -3.  5.]

Визначник матриці A: 1.0

Розклад вектора b за базисом:
  2.0000 * a_1
  -3.0000 * a_2
  5.0000 * a_3


array([ 2., -3.,  5.])

🧩 **4.7. Шифр Гілла.**

 У цій задачі ми познайомимося з шифром Гілла -- одним з методів шифрування інформації, і проведемо його лінійноалгебраїчний аналіз. Американський математик Лестер Гілл винайшов його 1929 року, і, хоча шифр виявився не дуже вдалим (далі ми поговоримо, з яких причин), він став важливою сходинкою в розвитку криптографії, оскільки продемонстрував, наскільки продуктивним може бути саме математичний підхід до цієї науки.

Для побудови шифру спочатку обирають алфавіт символів, з яких можуть складатися повідомлення, що їх треба шифрувати. Можна взяти деякий стандартний алфавіт, наприклад, латинський, в якому 26 літер, але зручніше використовувати алфавіт, кількість символів у якому є простим числом. Тому ми додамо до латинського алфавіту ще три символи:  '$\quad $'(пробіл), '.'(крапка), ','(кома) й використовуватимемо алфавіт з 29 символів. Символам алфавіту взаємно однозначно відповідають елементи поля $\mathbb{Z}_{29}$, що є класами лишків за модулем 29, але ми позначаємо їх як числа: A -- 0, B -- 1, C -- 2, ... , Z -- 25, '$\ $' -- 26, '.' -- 27, ',' -- 28. 

Учасників обміну повідомленнями в криптографії зазвичай називають Алісою та Бобом. Шифрування повідомлень здійснюється за допомогою ключа, яким володіють Аліса та Боб та тримають його в секреті. Шифр Гілла передбачає, що ключем є квадратна матриця (деякого порядку $n$), елементи якої беруться з поля $\mathbb{Z}_{29}$ (саме для того, щоб класи лишків утворили поле, ми й обрали 29 символів). Для того, щоб зашифрувати повідомлення й надіслати його Бобу, Аліса 

1. Розбиває повідомлення на блоки довжини $n$.
2. Переводить символи цих блоків у елементи поля $\mathbb{Z}_{29}$, отримуючи таким чином набір векторів довжини $n$: $u_1, \dots, u_s$.
3. Множить матрицю-ключ $K$ на кожен з векторів, отримуючи набір зашифрованих векторів: $Ku_1, \dots, Ku_s$.
4. Надсилає цей набір Бобу.

Щоб дешифрувати повідомлення (тобто зрозуміти, яким був вихідний текст), Бобу достатньо помножити кожен з векторів, що він їх отримав, на матрицю, обернену до матриці ключа: $K^{-1}$. Зокрема, обираючи матрицю-ключ, треба подбати про те, щоб вона була обертовною, тобто невиродженою над полем $\mathbb{Z}_{29}$.


1️⃣ Реалізуйте функції, що здійснюють шифрування та дешифрування Гілла. 
Передбачте допоміжні функції:

1. Функцію розбиття тексту на блоки певної довжини (якщо якийсь з блоків виявиться коротшим, то можна доповнити його деякою послідовністю символів).
2. Функції переведення текстових блоків у вектори з елементів поля $\mathbb{Z}_{29}$ (і навпаки).
3. Функцію перевірки того, що матриця-ключ є обертовною та знаходження оберненої матриці до матриці-ключа.

Протестуйте ваші функції та продемонструйте їхню роботу.

In [10]:
import numpy as np
from sympy import Matrix
from sympy import gcd  # використовуємо gcd із sympy

# 1. Алфавіт і відповідність символів елементам поля Z_29
alphabet = [chr(i) for i in range(65, 91)] + [' ', '.', ',']
char_to_num = {char: i for i, char in enumerate(alphabet)}
num_to_char = {i: char for char, i in char_to_num.items()}

# 2. Допоміжна функція: розбиття на блоки фіксованої довжини
def split_text(text, n):
    text = text.upper()
    padding = (n - len(text) % n) % n
    text += ' ' * padding  # доповнюємо пробілами
    return [text[i:i+n] for i in range(0, len(text), n)]

# 3. Текст <-> Вектор
def text_to_vector_block(block):
    return np.array([char_to_num[c] for c in block])

def vector_block_to_text(vec):
    return ''.join([num_to_char[int(x) % 29] for x in vec])

# 4. Перевірка на обертовність та знаходження оберненої матриці
def is_invertible_mod(matrix, mod=29):
    det = round(Matrix(matrix.tolist()).det()) % mod
    return det != 0 and gcd(det, mod) == 1

def inverse_mod_matrix(matrix, mod=29):
    sympy_matrix = Matrix(matrix.tolist())
    inv_matrix = sympy_matrix.inv_mod(mod)
    return np.array(inv_matrix.tolist()).astype(int)

# 5. Функція шифрування
def encrypt(text, key_matrix):
    n = key_matrix.shape[0]
    blocks = split_text(text, n)
    encrypted_blocks = []

    for block in blocks:
        vec = text_to_vector_block(block).reshape(-1, 1)
        enc_vec = key_matrix.dot(vec) % 29
        encrypted_blocks.append(enc_vec.flatten())

    return np.array(encrypted_blocks)

# 6. Функція дешифрування
def decrypt(encrypted_blocks, key_matrix):
    inv_key = inverse_mod_matrix(key_matrix, 29)
    decrypted_text = ""

    for vec in encrypted_blocks:
        vec = vec.reshape(-1, 1)
        dec_vec = inv_key.dot(vec) % 29
        decrypted_text += vector_block_to_text(dec_vec.flatten())

    return decrypted_text.strip()

# 7. Приклад роботи
key = np.array([[3, 10], [20, 9]])  # Простий ключ 2x2

if is_invertible_mod(key):
    msg = "HELLO, Alice from Bob"
    print("Оригінальне повідомлення:", msg)

    encrypted = encrypt(msg, key)
    print("Зашифроване повідомлення (вектори):")
    for vec in encrypted:
        print(vec)

    decrypted = decrypt(encrypted, key)
    print("Розшифроване повідомлення:", decrypted)
else:
    print("Матриця не є обертовною в Z_29.")


Оригінальне повідомлення: HELLO, Alice from Bob
Зашифроване повідомлення (вектори):
[3 2]
[27  0]
[ 3 10]
[20 27]
[26  2]
[17 18]
[12 14]
[17  2]
[ 6 10]
[27  1]
[ 2 22]
Розшифроване повідомлення: HELLO, ALICE FROM BOB


Далі ми поговоримо про те, чи є шифр Гілла стійким до зламу. Тобто, якщо ворог (якого в криптографії зазвичай називають Євою) перехопить зашифроване повідомлення, то наскільки легко йому буде розшифрувати повідомлення не володіючи попередньо секретним ключем.

2️⃣ Нехай Єва знає розмір матриці-ключа $n$ і намагається розшифрувати повідомлення, зробивши повний перебір усіх можливих матриць. Пригадаємо, що матриця-ключ є невиродженою над полем $\mathbb{Z}_{29}$, тобто її рядки є лінійно незалежними векторами у просторі $\mathbb{Z}_{29}^n$. Зясуйте, скільки матриць має перебрати Єва. Зробіть висновки, чи є метод ``грубої сили'' придатним до зламу шифра Гілла. 

### Кількість можливих обернених матриць-ключів над полем $\mathbb{Z}_{29}$

Шифр Гілла використовує як ключ квадратну матрицю розміру $n \times n$, елементи якої належать полю $\mathbb{Z}_{29}$. Щоб матриця була придатною для шифрування, вона повинна бути **оберненою** (невиродженою) в цьому полі.

Загальна формула для обчислення кількості обернених $n \times n$ матриць над полем з  $q$ елементів:

$$
|K| = q^{n^2} \cdot \prod_{i=1}^{n} \left(1 - \frac{1}{q^i} \right)
$$

Підставляючи \( q = 29 \), отримаємо:

$$
|K| = 29^{n^2} \cdot \left(1 - \frac{1}{29}\right) \left(1 - \frac{1}{29^2}\right) \cdots \left(1 - \frac{1}{29^n}\right)
$$



### Приклад: $n = 3$

Підставимо $n = 3$ у формулу:

$$
|GL(3, \mathbb{Z}_{29})| = (29^3 - 1)(29^3 - 29)(29^3 - 29^2)
$$

Обчислимо:

- $29^3 = 24389$
- $24389 - 1 = 24388$
- $24389 - 29 = 24360$
- $24389 - 841 = 23548$

$$
|K| = 24388 \times 24360 \times 23548 \approx 1.4 \times 10^{13}
$$


## Висновок

- Навіть для $n = 3$ кількість можливих ключів — понад $10^{13}$.
- Для $n = 4$ — це вже більше $10^{23}$.
- Це означає, що **груба сила** є **непрактичною** для будь-якого $n \geq 3$.



3️⃣ Нехай тепер для зламу шифру Єва спробує використати метод частотного аналізу. Метод полягає в тому, що в текстах різні символи зустрічаються з різними частотами. Наприклад, в україномовних текстах найчастіше вживається літера 'о', а в англомовних -- літери 't', 'e'. Обчислюючи частоти, з якими в зашифрованому тексті зустрічається той чи інший символ, можна висловити припущення, якому символу він відповідає у вихідному тексті. Приклад використання частотного аналізу можна зустріти в оповіданнях "Танцюючі чоловічки" Артура Конан Дойля і "Золотий жук" Едгара Алана По. А у реальному житті цим методом користувався, наприклад, французький історик Жан-Франсуа Шампольйон, розшифровуючи єгипетські ієрогліфи.

Поміркуйте над тим, чи варто Єві скористатися частотним аналізом, розшифровуючи шифр Гілла?

## 3️⃣ Чи можливо застосувати частотний аналіз до шифру Гілла?

## Ідея методу

Метод **частотного аналізу** базується на тому, що в будь-якій мові певні символи або комбінації символів зустрічаються **значно частіше**, ніж інші.

У шифрі Гілла текст шифрується **не посимвольно**, а **по блоках з $n$ символів**, які інтерпретуються як вектори в просторі $\mathbb{Z}_{29}^n$.

Припустимо, що відкритий текст розбитий на $s$ блоків довжини $n$:  
$$
u_1, u_2, \dots, u_s
$$
Зашифровані блоки:
$$
Ku_1, Ku_2, \dots, Ku_s
$$
де $K$ — матриця-ключ розміру $n \times n$ над $\mathbb{Z}_{29}$.

Тобто **один зашифрований символ залежить одразу від усього блоку з $n$ символів відкритого тексту**.


## Наслідки для частотного аналізу

Це означає:

- **Немає прямого відображення** між відкритими символами та зашифрованими — один символ шифротексту **не пов’язаний** з одним символом відкритого тексту.
- **Частоти окремих символів не зберігаються**.  
  Усі блоки відкритого тексту (навіть якщо це однакові слова) при різних $K$ можуть дати **абсолютно різні шифровані блоки**.



## Але чи можливо провести аналіз за блоками?

Якщо довжина блоку $n$ є невеликою (наприклад, $n = 2$ або $n = 3$), то:

- Можна здійснити **частотний аналіз для блоків з $n$ символів**.
- Наприклад, визначити, які блоки найчастіше зустрічаються в шифротексті.
- І припустити, що вони відповідають найпоширенішим словам або комбінаціям символів (наприклад: "на", "по", "the", "ing").

Проте кількість можливих блоків швидко зростає:

\( \text{Кількість блоків довжини } n = 29^n \)

Наприклад:

- $n = 2$: $29^2 = 841$ блок
- $n = 3$: $29^3 = 24\,389$ блоків

Чим більший $n$, тим **менше шансів**, що певний блок часто повторюватиметься — отже частотний аналіз **втрачає ефективність**.



## Висновок

- **Частотний аналіз на рівні символів — не працює** у шифрі Гілла, бо символи повністю "розмазуються" у блоках.
- **Частотний аналіз блоків** можливий лише при **малому $n$**, або якщо дані мають **повторювану структуру** (наприклад, однакові короткі слова).
- Тому **не рекомендується використовувати шифр Гілла для структурованих даних**, де часто повторюються однакові блоки (наприклад, назви, префікси, тощо).
- При **випадковому ключі** і достатньо великому $n$ (від $3$ і вище) — **частотний аналіз є неефективним засобом злому**.



 4️ Ще один підхід до зламу шифра Гілла передбачає перехоплення достатньо великої кількості повідомлень і застосування методу "відомого відкритого тексту". Метод полягає в тому, що часто можна зробити припущення про те, яка інформація точно має міститися в повідомленні. Наприклад, повідомлення зазвичай починається зі звернення "Привіт, Боб!", "Юстас Алексу" та таке інше. В оповіданні "Танцюючі чоловічки" Шерлок Голмс використав також і цей метод, припустивши, що повідомлення починаються з імені героїні.
 
 Якщо Єва знає, що має розшифрувати матрицю певного розміру $n$, то вона може вважати елементи цієї матриці невідомими. Далі, Єва має скласти систему умов вигляду $v=Ku$, де  $v$ -- фрагменти перехоплених повідомлень, а $u$ -- фрагменти вихідних повідомлень, про які Єва здогадується, чому вони дорівнюють (тобто $u, v$ вважаються відомими).

Поясніть, яким чином Єва зможе знайти матрицю $K$ з цих умов. Також поміркуйте над тим, скільки умов вигляду $v=Ku$ має скласти Єва, щоб це здійснити. 

## Метод «відомого відкритого тексту» для зламу шифра Гілла

## Ідея методу

У багатьох випадках ворог (Єва) може **знати або припускати**, який саме відкритий текст (або його частина) відповідає певному зашифрованому фрагменту. Це і є суть **методу відомого відкритого тексту**.

Зокрема, вона має:

- $u_1, \dots, u_s$ — фрагменти **відомого відкритого тексту**, представлені як вектори довжини $n$
- $v_1, \dots, v_s$ — відповідні **зашифровані вектори**, тобто фрагменти шифротексту

Модель шифрування для кожного блоку:
$$
v_i = K u_i, \quad i = 1, 2, \dots, s
$$
де $K$ — **матриця-ключ** розміру $n \times n$ над полем $\mathbb{Z}_{29}$.



## Як знайти матрицю $K$

Запишемо всі відомі пари $u_i, v_i$ у вигляді матриць:

- Нехай $U$ — матриця, утворена з векторів $u_i$ як **стовпців**:
$$
U = \begin{bmatrix} u_1 & u_2 & \dots & u_n \end{bmatrix}
$$
- Нехай $V = [v_1 \ v_2 \ \dots \ v_n]$ — відповідні зашифровані вектори

Маємо:
$$
V = K U
\quad \Rightarrow \quad
K = V U^{-1}
$$
тобто, щоб знайти $K$, Єва повинна:

1. Зібрати **$n$ лінійно незалежних векторів $u_i$**, які утворюють **невироджену** (обернену) матрицю $U$
2. Мати відповідні вектори $v_i$
3. Обчислити обернену матрицю $U^{-1}$ над полем $\mathbb{Z}_{29}$
4. Знайти ключ:  
$$
K = V U^{-1} \mod 29
$$


## Скільки умов потрібно?

Щоб відновити матрицю $K$ розміру $n \times n$, потрібно **щонайменше $n$ рівнянь** (векторів $u_i$), тобто:

- **$n$ відомих пар**: $u_i \leftrightarrow v_i$
- **$U$ має бути оберненою**, тобто її стовпці повинні бути **лінійно незалежними** у $\mathbb{Z}_{29}^n$

Якщо Єва має більше ніж $n$ відомих пар, вона може застосувати **методи надлишкової системи** — наприклад, розв’язати систему з допомогою методу найменших квадратів у модульній арифметиці (в символьному вигляді — через систему рівнянь).



## Висновок

- Метод відомого відкритого тексту **дуже ефективний**, якщо зловмисник має **достатню кількість фрагментів відкритого тексту**.
- Якщо $n$ — розмір блоку, то достатньо мати **$n$ лінійно незалежних пар** $u_i \leftrightarrow v_i$ для **повного відновлення ключа $K$**.
- Тому **небезпечно шифрувати шаблонні повідомлення**, які легко вгадати (наприклад, "Привіт, Боб!", "З повагою", тощо).


5️⃣ Зробіть загальний висновок, до яких способів зламу не є стійким шифр Гілла. Знайдіть інформацію (або придумайте самі) про те, як можна змінити шифр Гілла, щоб ускладнити його злам. Не забудьте вказати джерела.

Оригінальний шифр Хілла не знайшов практичного застосування в криптографії через слабку стійкість до зламу та відсутність опису алгоритмів генерації прямих і обернених матриць великого розміру. Більшість модифікованих криптосистем передбачають при шифруванні/дешифруванні використовувати не одну пару ключів, а кілька, що багаторазово підвищує стійкість системи. При шифруванні кожен блок відкритого тексту обробляється окремим ключем. Використання цього принципу дозволяє значною мірою приховати статистичні властивості відкритого і зашифрованого тексту, а також взаємозв’язок між ними. Нижче наведено кілька прикладів:

Халаф та інші запропонували трьохетапний модифікований алгоритм шифрування Хілла, де кожен етап розглядається як блочний шифр з довжиною блоку 128 біт і довжиною ключа 256 біт. Процес шифрування складається з трьох етапів, а ключі генеруються випадковим чином за допомогою генератора випадкових чисел. Отже, він більш надійний і забезпечує високий рівень безпеки даних, правда сильно програє за швидкістю.
1*

Мані та Вішвамбарі запропонували детермінований метод генерації ключової матриці на основі магічного прямокутника. Матриця ключів більшого порядку генерується на основі m. Щоб згенерувати матрицю ключів, спочатку магічний прямокутник порядку m × n перетворюється в магічний квадрат порядку m × m, з якого формується потрібна матриця ключів.
2*

Криптостійкість шифру Хілла можна підвищити, якщо використовувати змінну довжину ключа. Довжина відкритого тексту змінюється випадковим чином: m = 2^k (k = 3, 4, 5, …), внаслідок чого змінюються шифрувальні та дешифрувальні матриці.

Також було запропоновано варіант генерації ключа за допомогою LU-розкладу без дробів. Якщо взяти випадково згенеровану матрицю, отримати LU-розклад цієї матриці, то оскільки матриця L завжди обернена, вона може бути використана як ключ. Розглянемо цей процес детальніше:

Генерація ключа за допомогою LU-розкладу
Найбільшою проблемою в шифрі Хілла є пошук матриці, що відповідає ключу, яка має обернену матрицю. Одним зі способів розв’язання є генерація ключ-матриць за допомогою LU-розкладу (матриця L завжди обернена). Але матриці L і U можуть містити дроби, отже, вони не підходять для ключа. Проте це вирішується LU-розкладом без дробів. Ми можемо отримати LU-розклад матриці A без дробів у вигляді P × A = L × D⁻¹ × U, де P – матриця перестановок, а D – діагональна матриця. Це дуже складне завдання — вручну визначити LU-розклад без дробів за допомогою ручки та паперу. Але за допомогою комп’ютера це можна легко обчислити. Оскільки матриці L і U вільні від дробів, числа в матриці стають досить великими, а також мають змішані значення, такі як додатні цілі числа, від’ємні цілі числа і нулі, що ускладнює ключ.

Використані Джерела:

https://habr.com/en/articles/710890/

https://habr.com/en/articles/332714/

https://ru.onlinemschool.com/math/assistance/matrix/multiply/?oms_all=a%3d%7b%7b25,9,21%7d%7d,b%3d%7b%7b0,12,29%7d,%7b16,9,14%7d,%7b9,8,13%7d%7d
для обчислення матриць


1*  A triple hill cipher algorithm proposed to increase the security of encrypted binary data and its implementation using FPGA
ieeexplore.ieee.org


2*  Generation of Key Matrix for Hill Cipher Encryption Using Classical Cipher
ieeexplore.ieee.org

Також було використання штучного інтелекту для написання та фіксу помилок в коді, використовувався Chatgpt: https://chatgpt.com/