<a target="_blank" href="https://colab.research.google.com/github/LPolyakova/Linear_Algebra_for_CS_students/blob/main/CP/LA_CP_04_Linear_spaces.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# ЛА-Комп'ютерний практикум-04. Лінійні простори

In [1]:
# these imports may be useful

import pandas as pd
from scipy import linalg
import numpy as np
import matplotlib.pyplot as plt
from sympy import *                  #module to do symbolic calculations

 #### Деякі інструменти, що стануть у нагоді 

In [2]:
# these tools may be useful

# rank calculation
A = np.array([[1,2], [-1, -2], [2, 4]]) 
r = np.linalg.matrix_rank(A)
print(f"A={A}, \n rank(A) = {r}")

A=[[ 1  2]
 [-1 -2]
 [ 2  4]], 
 rank(A) = 1


## Вправи

💻  **4.1. Розклад за базисом.** Напишіть програму, яка перевіряє, чи є набір векторів $a_1, a_2, \dots, a_n$ базисом простору $\mathbb{R}^n$, і знаходить розклад вектора $b$ за цим базисом. Ви можете використовувати numpy.linalg.solve

In [1]:
#write your code here

import numpy as np
from numpy.linalg import LinAlgError

def is_basis_and_decompose(vectors, b):
    """
    vectors: список векторів (кожен вектор — список або np.array)
    b: вектор, який потрібно розкласти
    """

    A = np.column_stack(vectors)  # матриця, у якій вектори — стовпці
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)

    print("Матриця базису A:")
    print(A)
    print("\nВектор b:")
    print(b)

    try:
        # перевіримо, чи матриця невироджена (тобто det ≠ 0)
        det = np.linalg.det(A)
        print(f"\nВизначник матриці A: {det}")

        if np.isclose(det, 0):
            print("Вектори не утворюють базис: визначник дорівнює нулю.")
            return

        # Розв'язуємо A * x = b
        x = np.linalg.solve(A, b)
        print("\nРозклад вектора b за базисом:")
        for i, coeff in enumerate(x):
            print(f"  {coeff:.4f} * a_{i+1}")
        return x

    except LinAlgError as e:
        print("Помилка при обчисленні:", e)

# Приклад використання
a1 = [1, 0, 0]
a2 = [0, 1, 0]
a3 = [0, 0, 1]
b = [2, -3, 5]

vectors = [a1, a2, a3]
is_basis_and_decompose(vectors, b)


Матриця базису A:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Вектор b:
[ 2. -3.  5.]

Визначник матриці A: 1.0

Розклад вектора b за базисом:
  2.0000 * a_1
  -3.0000 * a_2
  5.0000 * a_3


array([ 2., -3.,  5.])

💻  **4.2.  Матриця переходу.** Напишіть програму, яка обчислює матрицю переходу від базису $e$ до базису $f$ і знаходить координати вектора, заданого в базисі $e$, у базисі $f$. Вважайте, що всі вектори задані як вектори-стовпці $\mathbb{R}^n$.

In [2]:
#write your code here

💻  **4.3. Лінійна оболонка.** Напишіть програму, яка для двох векторів у $\mathbb{R}^3$ створює масив лінійних комбінацій цих векторів і зображує у тривимірному просторі цей масив. Повинно вийти "точкове" зображення прямої або площини.


In [3]:
#write your code here

💻  **4.4. Випадкова матриця заданого рангу.** Для того, щоб згенерувати випадкову матрицю $m\times n$ із заданим рангом $r$ можна діяти наступним чином: знайти добуток випадкової матриці $m\times r$ і випадкової матриці $r\times n$. Проведіть експерименти, які підтверджують цей спосіб, тобто напишіть функцію, яка за заданими $m,n,r$ генерує випадкову матрицю описаним вище способом, згенеруйте за допомогою цієї функціїї кілька матриць, а потім знайдіть їх ранг і порівняйте. Чи можете ви пояснити, чому цей спосіб працює?  

In [4]:
#write your code here

💻  **4.5. Ранг і транспонування.** У математичній частині практикуму є задача про те, що ранги матриць  $A$, $A^t$, $A^tA$, $AA^t$ завжди однакові. Продемонструйте це декількома прикладами, згенерувавши випадкові матриці $A$ різних розмірів та рангів (використайте попередню задачу).

In [5]:
#write your code here

## Задачі

In [6]:
# import section

🧩 **4.6. Опукла оболонка.** У цій задачі ми поговоримо про поняття опуклої оболонки деякої підмножини в  $\mathbb{R}^n$. Опуклі оболонки мають числені застосування у статистиці, дискретній оптимізації, обчислюваній геометрії, тощо (див. https://en.wikipedia.org/wiki/Convex_hull), а отже, як наслідок, в аналізі даних, комп'ютерній графіці та інших наукоємних галузях програмування.

1️⃣ Якщо $a_1, a_2$ -- вектори простору $\mathbb{R}^n$ (які ми також розглядаємо просто як точки), то *відрізком* з кінцями у цих точках називається сукупність усіх точок, заданих векторами вигляду $x=\alpha_1a_1+\alpha_2a_2$, де $\alpha_1+\alpha_2=1, 0\leq \alpha_1, \alpha_2\leq 1$. Множина $M$ точок простору $\mathbb{R}^n$ називається *опуклою*, якщо для довільних двох точок цієї множини весь відрізок з кінцями в цих точках також належить множині $M$. Прикладами опуклих множин на площині можуть бути круги, еліпси, квадрати та інші правильні багатокутники, півплощини, прямі.

*Опуклою оболонкою* деякої множини точок $A$ з $\mathbb{R}^n$ називається перетин усіх опуклих множин, що містять  $A$ (див. мал.). Позначається $conv(A)$.

<img src='images\convex_hull.png' width=320, heigth=240>

Доведіть, що опукла оболонка скінченної системи точок $a_1, a_2, \dots, a_k$ з $\mathbb{R}^n$ складається з усіх точок, заданих векторами вигляду $x=\alpha_1a_1+\dots+\alpha_ka_k$,  де $\alpha_1+\dots+\alpha_k=1$ і $0\leq \alpha_i\leq 1 (i=1, \dots, k)$.

✔️ *Ваші міркування запишіть тут.*

2️⃣ Доведіть, що для скінченної множини точок $A= {a_1, \dots, a_k}$ площини (тобто у просторі $\mathbb{R}^2$) опукла оболонка є опуклим багатокутником з вершинами з множини $A$ (у вироджених випадках цей багатокутник може перетворитися на відрізок або точку). Також переконайтеся, що якщо через довільну сторону цього багатокутника провести пряму, то багатокутник (а отже, і вся множина $A$) виявиться розташованим по один бік від цієї прямої.

✔️ *Ваші міркування запишіть тут.*

3️⃣ Далі ми розглянемо алгоритм Джарвіса -- один з найпростіших алгоритмів, що будує опуклу оболонку скінченної множини точок на площині. Нехай на вході маємо множину точок $A= \{a_1, \dots, a_k\}$, а на виході хочемо отримати вершини $p_1, \dots, p_s\in A$ багатокутника, що є опуклою оболонкою $A$. Алгоритм ще називається "алгоритмом загортання подарунка" і складається з таких кроків:

1. Спочатку треба обрати початкову точку $p_1$, як точку з найменшою $y$-координатою (або найправішу з них, якщо таких точок кілька).

2. На кожному з наступних кроків для останньої зі знайдених вершин $p_i$ треба уявити, що $p_i$ є центром полярної системи координат, а полярною віссю вважати напрямок осі X, якщо $i=0$, або ж промінь, що починається з $p_i$ і є продовженням відрізка $p_{i-1}p_i$, якщо $i>0$. Далі знайти таку точку $p_{i+1}$, що ще не належить багатокутнику, і $p_{i+1}$ має найменший полярний кут в цій уявній системі (кут рахується від 0 до 360 проти годинникової стрілки). Якщо точок з найменшим полярним кутом кілька, то треба взяти ту з них, яка знаходиться на більшій відстані від $p_i$ (див. мал.)

5. Кроки треба повторювати до тих пір, поки ламана не замкнеться, тобто поки в послідовності побудованих вершин знов не зустрінеться точка $p_1$.

<img src='images\Graham.png' width=300, heigth=200>

Доведіть коректність алгоритму Джарвіса, тобто що він справді будує опуклу оболонку множини $A$. Оцініть його складність.

✔️ *Ваші міркування запишіть тут.*

4️ Реалізуйте алгоритм Джарвіса, протестуйте його та виведіть зображення декількох опуклих оболонок, що ви їх побудували.

In [7]:
#write your code here

5️⃣ Знайдіть інфо про інші алгоритми, що будують опуклі оболонки. Реалізуйте ще якійсь з алгоритмів, порівняйте з алгоритмом Джарвіса. Не забудьте вказати, який алгоритм ви реалізуєте і в чому полягає його суть.

In [8]:
#write your code here

🧩 **4.7. Шифр Гілла.**

 У цій задачі ми познайомимося з шифром Гілла -- одним з методів шифрування інформації, і проведемо його лінійноалгебраїчний аналіз. Американський математик Лестер Гілл винайшов його 1929 року, і, хоча шифр виявився не дуже вдалим (далі ми поговоримо, з яких причин), він став важливою сходинкою в розвитку криптографії, оскільки продемонстрував, наскільки продуктивним може бути саме математичний підхід до цієї науки.

Для побудови шифру спочатку обирають алфавіт символів, з яких можуть складатися повідомлення, що їх треба шифрувати. Можна взяти деякий стандартний алфавіт, наприклад, латинський, в якому 26 літер, але зручніше використовувати алфавіт, кількість символів у якому є простим числом. Тому ми додамо до латинського алфавіту ще три символи:  '$\quad $'(пробіл), '.'(крапка), ','(кома) й використовуватимемо алфавіт з 29 символів. Символам алфавіту взаємно однозначно відповідають елементи поля $\mathbb{Z}_{29}$, що є класами лишків за модулем 29, але ми позначаємо їх як числа: A -- 0, B -- 1, C -- 2, ... , Z -- 25, '$\ $' -- 26, '.' -- 27, ',' -- 28. 

Учасників обміну повідомленнями в криптографії зазвичай називають Алісою та Бобом. Шифрування повідомлень здійснюється за допомогою ключа, яким володіють Аліса та Боб та тримають його в секреті. Шифр Гілла передбачає, що ключем є квадратна матриця (деякого порядку $n$), елементи якої беруться з поля $\mathbb{Z}_{29}$ (саме для того, щоб класи лишків утворили поле, ми й обрали 29 символів). Для того, щоб зашифрувати повідомлення й надіслати його Бобу, Аліса 

1. Розбиває повідомлення на блоки довжини $n$.
2. Переводить символи цих блоків у елементи поля $\mathbb{Z}_{29}$, отримуючи таким чином набір векторів довжини $n$: $u_1, \dots, u_s$.
3. Множить матрицю-ключ $K$ на кожен з векторів, отримуючи набір зашифрованих векторів: $Ku_1, \dots, Ku_s$.
4. Надсилає цей набір Бобу.

Щоб дешифрувати повідомлення (тобто зрозуміти, яким був вихідний текст), Бобу достатньо помножити кожен з векторів, що він їх отримав, на матрицю, обернену до матриці ключа: $K^{-1}$. Зокрема, обираючи матрицю-ключ, треба подбати про те, щоб вона була обертовною, тобто невиродженою над полем $\mathbb{Z}_{29}$.


1️⃣ Реалізуйте функції, що здійснюють шифрування та дешифрування Гілла. 
Передбачте допоміжні функції:

1. Функцію розбиття тексту на блоки певної довжини (якщо якийсь з блоків виявиться коротшим, то можна доповнити його деякою послідовністю символів).
2. Функції переведення текстових блоків у вектори з елементів поля $\mathbb{Z}_{29}$ (і навпаки).
3. Функцію перевірки того, що матриця-ключ є обертовною та знаходження оберненої матриці до матриці-ключа.

Протестуйте ваші функції та продемонструйте їхню роботу.

In [9]:
#write your code here

Далі ми поговоримо про те, чи є шифр Гілла стійким до зламу. Тобто, якщо ворог (якого в криптографії зазвичай називають Євою) перехопить зашифроване повідомлення, то наскільки легко йому буде розшифрувати повідомлення не володіючи попередньо секретним ключем.

2️⃣ Нехай Єва знає розмір матриці-ключа $n$ і намагається розшифрувати повідомлення, зробивши повний перебір усіх можливих матриць. Пригадаємо, що матриця-ключ є невиродженою над полем $\mathbb{Z}_{29}$, тобто її рядки є лінійно незалежними векторами у просторі $\mathbb{Z}_{29}^n$. Зясуйте, скільки матриць має перебрати Єва. Зробіть висновки, чи є метод ``грубої сили'' придатним до зламу шифра Гілла. 

✔️ *Ваші міркування запишіть тут.*

3️⃣ Нехай тепер для зламу шифру Єва спробує використати метод частотного аналізу. Метод полягає в тому, що в текстах різні символи зустрічаються з різними частотами. Наприклад, в україномовних текстах найчастіше вживається літера 'о', а в англомовних -- літери 't', 'e'. Обчислюючи частоти, з якими в зашифрованому тексті зустрічається той чи інший символ, можна висловити припущення, якому символу він відповідає у вихідному тексті. Приклад використання частотного аналізу можна зустріти в оповіданнях "Танцюючі чоловічки" Артура Конан Дойля і "Золотий жук" Едгара Алана По. А у реальному житті цим методом користувався, наприклад, французький історик Жан-Франсуа Шампольйон, розшифровуючи єгипетські ієрогліфи.

Поміркуйте над тим, чи варто Єві скористатися частотним аналізом, розшифровуючи шифр Гілла?

✔️ *Ваші міркування запишіть тут.*

 4️ Ще один підхід до зламу шифра Гілла передбачає перехоплення достатньо великої кількості повідомлень і застосування методу "відомого відкритого тексту". Метод полягає в тому, що часто можна зробити припущення про те, яка інформація точно має міститися в повідомленні. Наприклад, повідомлення зазвичай починається зі звернення "Привіт, Боб!", "Юстас Алексу" та таке інше. В оповіданні "Танцюючі чоловічки" Шерлок Голмс використав також і цей метод, припустивши, що повідомлення починаються з імені героїні.
 
 Якщо Єва знає, що має розшифрувати матрицю певного розміру $n$, то вона може вважати елементи цієї матриці невідомими. Далі, Єва має скласти систему умов вигляду $v=Ku$, де  $v$ -- фрагменти перехоплених повідомлень, а $u$ -- фрагменти вихідних повідомлень, про які Єва здогадується, чому вони дорівнюють (тобто $u, v$ вважаються відомими).

Поясніть, яким чином Єва зможе знайти матрицю $K$ з цих умов. Також поміркуйте над тим, скільки умов вигляду $v=Ku$ має скласти Єва, щоб це здійснити. 

✔️ *Ваші міркування запишіть тут.*

5️⃣ Зробіть загальний висновок, до яких способів зламу не є стійким шифр Гілла. Знайдіть інформацію (або придумайте самі) про те, як можна змінити шифр Гілла, щоб ускладнити його злам. Не забудьте вказати джерела.

✔️ *Ваші міркування запишіть тут.*